### ISSUE TITLE
Fix travis CI

### ISSUE THREAD

**Issue by hikhvar** [inovex/trovilo#9]
Currently the CI run fails in the publish state. This should be fixed.

**Comment by hikhvar** [comment]
https://github.com/inovex/mqtt-stresser/pull/10 This CI failure seems to be related.

**Comment by bechtoldt** [comment]
created docker hub project, updated travis CI docker credentials 👍 

https://travis-ci.org/inovex/mqtt-stresser/builds/419549752 🎉 

=> https://hub.docker.com/r/inovex/mqtt-stresser/tags/
